package views;

import views.*;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.reservation;
import models.user;

public class Gestion_reservation_add extends javax.swing.JFrame
{
    Index old_layout;
    Gestion_reservation back_layout;
    boolean mode_edit = false;
    reservation element_array = null;
    
    public Gestion_reservation_add(Index old_layout, Gestion_reservation back_layout) {
        initComponents();
        
        this.old_layout = old_layout;
        this.back_layout = back_layout;
        
        this.mode_edit = false;
        
        element_array = new reservation();
        
        refresh_users();
        refresh_chambres();
        refresh_etats();
    }
    
    public Gestion_reservation_add(Index old_layout, Gestion_reservation back_layout, boolean mode_edit, String utilisateur_id) {
        initComponents();
        
        this.old_layout = old_layout;
        this.back_layout = back_layout;
        
        this.mode_edit = mode_edit;
        this.Button_add_new_student.setText("Modifier");
        
        
        refresh_users();
        refresh_chambres();
        refresh_etats();
        
        element_array = old_layout.db_.getreservationByreservationId(Integer.parseInt(utilisateur_id));
        
        this.user_id.getModel().setSelectedItem(new ComboItem(element_array.getUser_id().getUserFullName(), 
                String.valueOf(element_array.getUser_id().getUser_id())));
        
        this.chambre_id.getModel().setSelectedItem(new ComboItem(element_array.getChambre_id().getChambre_nom(), 
                String.valueOf(element_array.getChambre_id().getChambre_id())));
        
        this.reservation_date.setText(element_array.getReservation_date());
        this.reservation_etat.getModel().setSelectedItem(element_array.getReservation_etat());
    }
    
    public void refresh_chambres() {
        for (int i = 0; i < old_layout.db_.list_chambre().size(); i++) {
            String chambre_id = String.valueOf(old_layout.db_.list_chambre().get(i).getChambre_id());
            String chambre_full_name = String.valueOf(old_layout.db_.list_chambre().get(i).getChambre_nom());
            
            this.chambre_id.addItem(new ComboItem(chambre_full_name, chambre_id));
        }
    }
    
    public void refresh_users() {
        for (int i = 0; i < old_layout.db_.list_users().size(); i++) {
            String user_id = String.valueOf(old_layout.db_.list_users().get(i).getUser_id());
            String user_full_name = String.valueOf(old_layout.db_.list_users().get(i).getUser_nom()) + " " + 
                    String.valueOf(old_layout.db_.list_users().get(i).getUser_prenom());
            
            this.user_id.addItem(new ComboItem(user_full_name, user_id));
        }
        
        if (old_layout.user_array.getUser_type().equals("client")) {
            this.user_id.setVisible(false);
        }
    }
    
    public void refresh_etats() {
        this.reservation_etat.addItem("En-attend-Payement");
        this.reservation_etat.addItem("Payé");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_id = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Button_add_new_student = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        reservation_date = new javax.swing.JTextField();
        error_message = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chambre_id = new javax.swing.JComboBox();
        reservation_etat = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Hotels");

        jLabel4.setText("Client");

        Button_add_new_student.setText("Ajouté Nouveau");
        Button_add_new_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_add_new_studentActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        jLabel6.setText("Chambre");

        jLabel7.setText("Etat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_add_new_student))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservation_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(9, 9, 9)
                                            .addComponent(reservation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chambre_id, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chambre_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addComponent(reservation_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reservation_etat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(Button_add_new_student)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static boolean isDateValid(String date)
    {
        String DATE_FORMAT = "yyyy-MM-dd";
        try {
            DateFormat df = new SimpleDateFormat(DATE_FORMAT);
            df.setLenient(false);
            df.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    
    private void Button_add_new_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_add_new_studentActionPerformed
        if( this.reservation_date.getText().equals("") )
        {
            this.error_message.setText("error...ecrire la date");
        }
        else if( !isDateValid(this.reservation_date.getText()) )
        {
            this.error_message.setText("error... la date ne sont pas a ce format yyyy-mm-dd");
        }
        else
        {
            Object unit_id_object = user_id.getSelectedItem();
            String user_id_ = ((ComboItem)unit_id_object).getValue();
            
            Object chambre_id_object = chambre_id.getSelectedItem();
            String chambre_id_ = ((ComboItem)chambre_id_object).getValue();
            
            if( this.mode_edit )
            {
                String old_reservation_date = element_array.getReservation_date();
                
                element_array.setUser_id( old_layout.db_.getUserByUserId(Integer.parseInt(user_id_)) );
                element_array.setChambre_id( old_layout.db_.getchambreBychambreId(Integer.parseInt(chambre_id_)) );
                element_array.setReservation_date( String.valueOf(this.reservation_date.getText()) );
                element_array.setReservation_etat( String.valueOf(this.reservation_etat.getSelectedItem()) );
                
                if (!old_reservation_date.equals(element_array.getReservation_date()) ) {
                    if ( !old_layout.db_.check_available_date(old_layout.db_.getchambreBychambreId(Integer.parseInt(chambre_id_)), 
                        this.reservation_date.getText()) ) {
                        this.error_message.setText("error... la date ne pas disponible");
                        
                        return;
                    }
                }
                
                old_layout.db_.edit_reservation(element_array);

                back_layout.refresh_table();

                this.setVisible(false);
            }
            else
            {
                reservation new_reservation = new reservation();
                new_reservation.setReservation_id(old_layout.db_.list_reservation().size() + 1);
                new_reservation.setUser_id( old_layout.db_.getUserByUserId(Integer.parseInt(user_id_)) );
                new_reservation.setChambre_id( old_layout.db_.getchambreBychambreId(Integer.parseInt(chambre_id_)) );
                new_reservation.setReservation_date( String.valueOf(this.reservation_date.getText()) );
                new_reservation.setReservation_etat( String.valueOf(this.reservation_etat.getSelectedItem()) );
                
                if ( !old_layout.db_.check_available_date(old_layout.db_.getchambreBychambreId(Integer.parseInt(chambre_id_)), 
                        this.reservation_date.getText()) ) {
                    this.error_message.setText("error... la date ne pas disponible");
                }
                else
                {
                    

                    old_layout.db_.ajouter_reservation(new_reservation);

                    back_layout.refresh_table();

                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_Button_add_new_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_reservation_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_reservation_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_reservation_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_reservation_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_reservation_add(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_add_new_student;
    private javax.swing.JComboBox chambre_id;
    private javax.swing.JLabel error_message;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField reservation_date;
    private javax.swing.JComboBox reservation_etat;
    private javax.swing.JComboBox user_id;
    // End of variables declaration//GEN-END:variables
}
