/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.HashMap;
import java.util.Map;
import models.user;

public class Gestion_Utilisateur extends javax.swing.JPanel {
    Index old_layout;
    /**
     * Creates new form NewJPanel
     */
    public Gestion_Utilisateur(Index old_layout) {
        initComponents();
        
        this.old_layout = old_layout;
        
        this.refresh_table();
    }
    
    public void refresh_table()
    {
        Map<Integer, user> list_users = old_layout.db_.list_users();
        
        Object[][] data = new Object[list_users.size()][6];
        
        if (list_users.size() > 0)
        {
            int i = 0;
            for (int j = 0; j < list_users.size(); j++) {
                data[j][0] = list_users.get(j).getUser_id();
                data[j][1] = list_users.get(j).getUser_login();
                data[j][2] = list_users.get(j).getUser_nom();
                data[j][3] = list_users.get(j).getUser_prenom();
                data[j][4] = list_users.get(j).getUser_type();
            }
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "ID", "Login", "Nom", "Prenom", "Type"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question_1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        header_button_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        header_button_edit = new javax.swing.JButton();
        header_button_add = new javax.swing.JButton();

        header_button_delete.setBackground(new java.awt.Color(204, 0, 0));
        header_button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delete Bin_32px.png"))); // NOI18N
        header_button_delete.setText("Supprimer");
        header_button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_button_deleteMousePressed(evt);
            }
        });
        header_button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                header_button_deleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "test"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        header_button_edit.setBackground(new java.awt.Color(255, 153, 51));
        header_button_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit File_32px.png"))); // NOI18N
        header_button_edit.setText("Modifier");
        header_button_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_button_editMousePressed(evt);
            }
        });
        header_button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                header_button_editActionPerformed(evt);
            }
        });

        header_button_add.setBackground(new java.awt.Color(0, 102, 102));
        header_button_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Plus_32px.png"))); // NOI18N
        header_button_add.setText("Ajouter ");
        header_button_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_button_addMousePressed(evt);
            }
        });
        header_button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                header_button_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header_button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header_button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header_button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header_button_add)
                    .addComponent(header_button_delete)
                    .addComponent(header_button_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void header_button_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_button_deleteMousePressed
        if(jTable1.getSelectedRowCount() == 1)
        {
            String ref = jTable1.getValueAt(jTable1.getSelectedRows()[0], 0).toString();

            int dialogButton = jOptionPane1.YES_NO_OPTION;
            int dialogResult = jOptionPane1.showConfirmDialog (null, "Souhaitez-vous supprimer cet enregistrement?", "Warning", dialogButton);
            if(dialogResult == jOptionPane1.YES_OPTION){
                old_layout.db_.delete_user(Integer.parseInt(ref));
                this.refresh_table();
            }
        }
    }//GEN-LAST:event_header_button_deleteMousePressed

    private void header_button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_header_button_deleteActionPerformed

    }//GEN-LAST:event_header_button_deleteActionPerformed

    private void header_button_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_button_editMousePressed
        
    }//GEN-LAST:event_header_button_editMousePressed

    private void header_button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_header_button_editActionPerformed
        if(jTable1.getSelectedRowCount() == 1)
        {
            String ref = jTable1.getValueAt(jTable1.getSelectedRows()[0], 0).toString();
            
            new Gestion_Utilisateur_add(old_layout, this, true, ref).setVisible(true);
        }
    }//GEN-LAST:event_header_button_editActionPerformed

    private void header_button_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_button_addMousePressed
        
    }//GEN-LAST:event_header_button_addMousePressed

    private void header_button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_header_button_addActionPerformed
        Gestion_Utilisateur_add a = new Gestion_Utilisateur_add(old_layout, this);
        a.setVisible(true);
    }//GEN-LAST:event_header_button_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton header_button_add;
    private javax.swing.JButton header_button_delete;
    private javax.swing.JButton header_button_edit;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.ButtonGroup question_1;
    // End of variables declaration//GEN-END:variables
}
