package views;

import controllers.Control;
import java.awt.Component;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;
import models.user;

/**
 *
 * @author Abdou
 */
public class Index extends javax.swing.JFrame {
    public Control db_ = null;
    public user user_array = null;
    
    public Index(user user_array) {
        initComponents();
        
        //db = new Database("gestion_paie", "paie_", Config.temp_table);
        
        this.user_array = user_array;
        //System.out.println(user_array.size());
        
        Control db_ = new Control();
        
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/resources/abgrcs_logo.png")).getImage());

            this.load_page(new Acceill(this));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    public Index() {
        initComponents();
        
        db_ = new Control();
        
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/resources/abgrcs_logo.png")).getImage());

            this.load_page(new Acceill(this));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    public void set_user_array(user user_array) {
        this.user_array = user_array;
        
        if (user_array.getUser_type().equals("client")) {
            this.gestion_utilisateurs4.setEnabled(false);
            this.gestion_utilisateurs.setEnabled(false);
        }
    }
    
    public void load_page(Component page_to_add)
    {
        Jpabel_main.removeAll();
        Jpabel_main.revalidate();
        Jpabel_main.repaint();
        
        Jpabel_main.setLayout(new GridLayout());
        Jpabel_main.add(page_to_add);
        Jpabel_main.revalidate();
        Jpabel_main.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Jpabel_main = new javax.swing.JPanel();
        gestion_utilisateurs = new javax.swing.JButton();
        gestion_utilisateurs4 = new javax.swing.JButton();
        gestion_utilisateurs5 = new javax.swing.JButton();
        gestion_utilisateurs7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Hotels");

        Jpabel_main.setMinimumSize(new java.awt.Dimension(826, 450));

        javax.swing.GroupLayout Jpabel_mainLayout = new javax.swing.GroupLayout(Jpabel_main);
        Jpabel_main.setLayout(Jpabel_mainLayout);
        Jpabel_mainLayout.setHorizontalGroup(
            Jpabel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Jpabel_mainLayout.setVerticalGroup(
            Jpabel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gestion_utilisateurs.setBackground(new java.awt.Color(255, 153, 51));
        gestion_utilisateurs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconfinder_88_171447.png"))); // NOI18N
        gestion_utilisateurs.setText("Utilisateurs");
        gestion_utilisateurs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestion_utilisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestion_utilisateursMousePressed(evt);
            }
        });
        gestion_utilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_utilisateursActionPerformed(evt);
            }
        });

        gestion_utilisateurs4.setBackground(new java.awt.Color(255, 153, 51));
        gestion_utilisateurs4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconfinder_friend_group_people_team_members_3994366.png"))); // NOI18N
        gestion_utilisateurs4.setText("Chambres");
        gestion_utilisateurs4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestion_utilisateurs4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestion_utilisateurs4MousePressed(evt);
            }
        });
        gestion_utilisateurs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_utilisateurs4ActionPerformed(evt);
            }
        });

        gestion_utilisateurs5.setBackground(new java.awt.Color(255, 153, 51));
        gestion_utilisateurs5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iconfinder_home_1265dd72.png"))); // NOI18N
        gestion_utilisateurs5.setText("Acceil");
        gestion_utilisateurs5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestion_utilisateurs5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestion_utilisateurs5MousePressed(evt);
            }
        });
        gestion_utilisateurs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_utilisateurs5ActionPerformed(evt);
            }
        });

        gestion_utilisateurs7.setBackground(new java.awt.Color(255, 153, 51));
        gestion_utilisateurs7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/planning_time.png"))); // NOI18N
        gestion_utilisateurs7.setText("Reservations");
        gestion_utilisateurs7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gestion_utilisateurs7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestion_utilisateurs7MousePressed(evt);
            }
        });
        gestion_utilisateurs7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_utilisateurs7ActionPerformed(evt);
            }
        });

        jMenu3.setText("Deconnextion");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });

        jMenuItem2.setText("Deconnextion");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gestion_utilisateurs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestion_utilisateurs4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gestion_utilisateurs5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(gestion_utilisateurs7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jpabel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jpabel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gestion_utilisateurs5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gestion_utilisateurs4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gestion_utilisateurs7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gestion_utilisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestion_utilisateursMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestion_utilisateursMousePressed
        
    }//GEN-LAST:event_gestion_utilisateursMousePressed

    private void gestion_utilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_utilisateursActionPerformed
        this.load_page(new Gestion_Utilisateur(this));
    }//GEN-LAST:event_gestion_utilisateursActionPerformed

    private void gestion_utilisateurs4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestion_utilisateurs4MousePressed
        
    }//GEN-LAST:event_gestion_utilisateurs4MousePressed

    private void gestion_utilisateurs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_utilisateurs4ActionPerformed
        this.load_page(new Gestion_Chambres(this));
    }//GEN-LAST:event_gestion_utilisateurs4ActionPerformed

    private void gestion_utilisateurs5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestion_utilisateurs5MousePressed
        
    }//GEN-LAST:event_gestion_utilisateurs5MousePressed

    private void gestion_utilisateurs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_utilisateurs5ActionPerformed
        this.load_page(new Acceill(this));
    }//GEN-LAST:event_gestion_utilisateurs5ActionPerformed

    private void gestion_utilisateurs7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestion_utilisateurs7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestion_utilisateurs7MousePressed

    private void gestion_utilisateurs7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_utilisateurs7ActionPerformed
        this.load_page(new Gestion_reservation(this));
    }//GEN-LAST:event_gestion_utilisateurs7ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked

    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new Login(this).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpabel_main;
    private javax.swing.JButton gestion_utilisateurs;
    private javax.swing.JButton gestion_utilisateurs4;
    private javax.swing.JButton gestion_utilisateurs5;
    private javax.swing.JButton gestion_utilisateurs7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
