package views;

import views.Index;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.spec.KeySpec;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;

public class Login extends javax.swing.JFrame {
    boolean mode_developer = false;
    Index a = null;
    
    public Login() {
        initComponents();
        
        this.result.setVisible(false);
        
        if (mode_developer == true)
        {
            this.user_login.setText("admin");
            this.user_pass.setText("admin");
        }
        
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/resources/abgrcs_logo.png")).getImage());
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    public Login(Index a) {
        initComponents();
        this.a = a;
        
        this.result.setVisible(false);
        
        if (mode_developer == true)
        {
            this.user_login.setText("admin");
            this.user_pass.setText("admin");
        }
        
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/resources/abgrcs_logo.png")).getImage());
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        loginbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user_login = new javax.swing.JTextField();
        user_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Hotels");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbutton.setBackground(new java.awt.Color(0, 102, 102));
        loginbutton.setText("Se connecter");
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbuttonMousePressed(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 105, -1, 20));

        result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setText("Le nom ou le mot de pass est incorrect.");
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mot de passe ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 145, 90, 20));

        user_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_loginActionPerformed(evt);
            }
        });
        user_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_loginKeyPressed(evt);
            }
        });
        getContentPane().add(user_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 160, 30));

        user_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_passKeyPressed(evt);
            }
        });
        getContentPane().add(user_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        this.loginbutton.setEnabled(false);
        this.result.setVisible(false);
        
        if( a == null )
            a = new Index();
        
        if( a.db_.user_exists_by_login(this.user_login.getText(), this.user_pass.getText()) )
        {
            a.set_user_array( a.db_.getUserByLoginName(this.user_login.getText()) );
            
            a.load_page(new Acceill(a));
            a.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.result.setVisible(true);
        }
        
        this.loginbutton.setEnabled(true);
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void loginbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMousePressed
        
        
    }//GEN-LAST:event_loginbuttonMousePressed

    private void user_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_loginActionPerformed

    private void user_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_loginKeyPressed
        this.loginbutton.setEnabled(false);
        this.result.setVisible(false);
        
        if( a.db_.user_exists_by_login(this.user_login.getText(), this.user_pass.getText()) )
        {
            a.load_page(new Acceill(a));
            a.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            this.result.setVisible(true);
        }
        
        this.loginbutton.setEnabled(true);
    }//GEN-LAST:event_user_loginKeyPressed

    private void user_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_passKeyPressed
        
    }//GEN-LAST:event_user_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel result;
    private javax.swing.JTextField user_login;
    private javax.swing.JPasswordField user_pass;
    // End of variables declaration//GEN-END:variables
}
